### ISSUE TITLE
Description datasets in data() not informative

### ISSUE THREAD

**Issue by jandeneve** [CenterForStatistics-UGent/pim#4]
See data(): description is not informative. 
In typical R: 

AirPassengers             Monthly Airline Passenger Numbers 1949-1960
BJsales                   Sales Data with Leading Indicator
BJsales.lead (BJsales)    Sales Data with Leading Indicator
BOD                       Biochemical Oxygen Demand

In pim

- [x] DysData                   This is the Dysphagia data
- [x] EngelData                 This is the engel data
- [x] FEVData                   This is the Childhood respiratory disease data
- [x] MHData                    This is the Mental health data
- [x] SUData                    This is the Surgical unit data

**Comment by JoFAM** [comment]
This is copied from the help pages. Adjust there (see also https://github.com/CenterForStatistics-UGent/pim/issues/6 ) for updating the description in data()

**Comment by JoFAM** [comment]
dysphagia data updated with commit 547ba44bdf60dfefb597c18cf149d3afb6ee5b66.

**Comment by JoFAM** [comment]
FEVData updated with commit 10b3a13687d0c6ff69f368c022438343c0a94bb6

**Comment by JoFAM** [comment]
EngelData updated with commit bad320bb007a0ca2de22d6edee5a7a136b7004b2

**Comment by JoFAM** [comment]
MHData updated with commit  fee6daf

**Comment by JoFAM** [comment]
SUData is removed from the package per agreement on the meeting with @jandeneve and Olivier a few months ago.  in commit 4e0da1d6c91b03c96628b2d679e1616abb20da6a
