### ISSUE TITLE
Can we use Nick his data

### ISSUE THREAD

**Issue by jandeneve** [CenterForStatistics-UGent/pim#5]
Do we have permission to use DysData  and SUData?

**Comment by JoFAM** [comment]
Mailed him and asked.

**Comment by JoFAM** [comment]
Is answered: As all data is published before, there shouldn't be any problem. Plus, it's all available in the old pim package as well, so turning it back now might be a tiny tad late.

Leave as is.

**Comment by JoFAM** [comment]
Must be checked, because the data itself was not published yet. Me mails.

**Comment by JoFAM** [comment]
Answer is: yes.
